version: '3.5'
services:
  mysql:
    container_name: slotcar-db
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3339:3306"
networks:
  default:
    name: slotcar

