version: '3.5'
services:
  php:
    container_name: slotcar-php
    build: ./docker/php-fpm
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
  web:
    container_name: slotcar-web
    image: nginx:latest
    ports:
      - "8889:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  mysql:
    container_name: slotcar-db
    image: mysql:8.0
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3335:3306"
networks:
  default:
    name: slotcar

