app_original_car_index:
    path: /
    method: [ GET ]
    controller: App\Controller\OriginalCarController::index

app_original_car_new:
    path: /new
    method: [ GET, POST ]
    controller: App\Controller\OriginalCarController::new

app_original_car_show:
    path: /{ulid}
    method: [ GET ]
    controller: App\Controller\OriginalCarController::show

app_original_car_edit:
    path: /{ulid}/edit
    method: [ GET, POST ]
    controller: App\Controller\OriginalCarController::edit

app_original_car_delete:
    path: /{ulid}
    method: [ POST ]
    controller: App\Controller\OriginalCarController::delete



